
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";



import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const AdventureDetail = lazy(() => import("./pages/AdventureDetail.tsx"));
const Adventures = lazy(() => import("./pages/Adventures.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const Blogs = lazy(() => import("./pages/Blogs.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/adventure-detail", element: <AdventureDetail />},
	{ path: "/adventuredetail", element: <AdventureDetail />},
	{ path: "/adventures", element: <Adventures />},
	{ path: "/", element: <App />},
	{ path: "/blogs", element: <Blogs />},
	{ path: "/contact", element: <Contact />},

];
